<?php

namespace MvpShop\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20180204163818 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $fixtures = "INSERT INTO product (name, description, price, created_at) VALUES ('Sugar - Icing', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', '3.73', '2017-08-03 07:24:26');
            INSERT INTO product (name, description, price, created_at) VALUES ('Basil - Primerba, Paste', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', '5.49', '2017-12-24 00:19:06');
            INSERT INTO product (name, description, price, created_at) VALUES ('Sole - Fillet', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '4.42', '2017-06-26 00:01:03');
            INSERT INTO product (name, description, price, created_at) VALUES ('Chicken - Whole Fryers', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.', '1.59', '2017-02-23 04:26:10');
            INSERT INTO product (name, description, price, created_at) VALUES ('Extract - Rum', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', '8.86', '2017-04-15 14:44:30');
            INSERT INTO product (name, description, price, created_at) VALUES ('Lettuce - Boston Bib - Organic', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', '6.57', '2017-04-04 19:15:52');
            INSERT INTO product (name, description, price, created_at) VALUES ('Carbonated Water - Blackberry', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', '6.71', '2017-05-26 10:08:59');
            INSERT INTO product (name, description, price, created_at) VALUES ('Vinegar - Sherry', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.', '7.27', '2017-05-10 08:07:04');
            INSERT INTO product (name, description, price, created_at) VALUES ('Juice - V8 Splash', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', '1.70', '2017-08-02 20:13:58');
            INSERT INTO product (name, description, price, created_at) VALUES ('Bar Special K', 'Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', '1.24', '2017-12-31 06:55:32');
            INSERT INTO product (name, description, price, created_at) VALUES ('Cloves - Ground', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '1.90', '2017-03-19 09:46:06');
            INSERT INTO product (name, description, price, created_at) VALUES ('Table Cloth 62x114 Colour', 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '5.07', '2017-06-13 21:15:48');
            INSERT INTO product (name, description, price, created_at) VALUES ('Juice - Tomato, 48 Oz', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', '5.94', '2017-06-09 02:47:28');
            INSERT INTO product (name, description, price, created_at) VALUES ('Bread - Frozen Basket Variety', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '7.53', '2017-10-01 22:20:08');
            INSERT INTO product (name, description, price, created_at) VALUES ('Bread - Raisin Walnut Pull', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '5.18', '2017-11-19 12:47:29');
            INSERT INTO product (name, description, price, created_at) VALUES ('Mushroom - Shitake, Dry', 'Aliquam erat volutpat. In congue.', '0.36', '2017-02-13 21:14:32');
            INSERT INTO product (name, description, price, created_at) VALUES ('Bok Choy - Baby', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '1.75', '2017-09-22 06:59:08');
            INSERT INTO product (name, description, price, created_at) VALUES ('Tray - 16in Rnd Blk', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.', '5.98', '2017-07-29 18:07:16');
            INSERT INTO product (name, description, price, created_at) VALUES ('Pastry - Key Limepoppy Seed Tea', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '4.77', '2018-01-06 20:14:30');
            INSERT INTO product (name, description, price, created_at) VALUES ('Tofu - Firm', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', '3.54', '2017-07-06 09:10:19');
            INSERT INTO product (name, description, price, created_at) VALUES ('Pork - Tenderloin, Frozen', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', '4.94', '2017-05-08 00:39:26');
            INSERT INTO product (name, description, price, created_at) VALUES ('Greens Mustard', 'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', '5.40', '2017-06-24 13:53:54');
            INSERT INTO product (name, description, price, created_at) VALUES ('Sauce - Roasted Red Pepper', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', '1.90', '2017-06-28 21:25:28');
            INSERT INTO product (name, description, price, created_at) VALUES ('Phyllo Dough', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '8.28', '2017-09-10 08:54:11');
            INSERT INTO product (name, description, price, created_at) VALUES ('Wine - Rubyport', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '8.16', '2017-08-31 00:29:19');
            INSERT INTO product (name, description, price, created_at) VALUES ('Calypso - Strawberry Lemonade', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2.25', '2017-05-10 18:33:30');
            INSERT INTO product (name, description, price, created_at) VALUES ('Kumquat', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', '3.14', '2017-08-20 13:42:04');
            INSERT INTO product (name, description, price, created_at) VALUES ('Wine - Fat Bastard Merlot', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '3.61', '2017-09-14 00:21:07');
            INSERT INTO product (name, description, price, created_at) VALUES ('Potatoes - Instant, Mashed', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '2.51', '2018-01-15 21:45:20');
            INSERT INTO product (name, description, price, created_at) VALUES ('Samosa - Veg', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', '6.26', '2017-10-23 00:09:38');
            INSERT INTO product (name, description, price, created_at) VALUES ('Maple Syrup', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '4.65', '2017-03-18 13:03:13');
            INSERT INTO product (name, description, price, created_at) VALUES ('Momiji Oroshi Chili Sauce', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', '9.72', '2017-10-29 11:11:06');
            INSERT INTO product (name, description, price, created_at) VALUES ('Cup - 4oz Translucent', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', '3.20', '2017-07-04 22:36:57');
            INSERT INTO product (name, description, price, created_at) VALUES ('Flour - Cake', 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', '8.44', '2017-11-08 18:12:11');
            INSERT INTO product (name, description, price, created_at) VALUES ('Beef - Short Loin', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.', '6.77', '2017-06-15 17:13:44');
            INSERT INTO product (name, description, price, created_at) VALUES ('Beer - Maudite', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '8.67', '2017-03-17 09:38:16');
            INSERT INTO product (name, description, price, created_at) VALUES ('Tortillas - Flour, 10', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '4.46', '2017-07-02 21:05:21');
            INSERT INTO product (name, description, price, created_at) VALUES ('Huck White Towels', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.', '8.28', '2017-02-25 06:54:06');
            INSERT INTO product (name, description, price, created_at) VALUES ('Cheese - Oka', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', '0.84', '2017-04-15 23:56:16');
            INSERT INTO product (name, description, price, created_at) VALUES ('Venison - Liver', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', '2.50', '2017-10-06 07:23:49');
            INSERT INTO product (name, description, price, created_at) VALUES ('Vaccum Bag 10x13', 'In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', '6.95', '2017-05-28 08:55:48');
            INSERT INTO product (name, description, price, created_at) VALUES ('Quiche Assorted', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '0.99', '2017-02-20 06:00:08');
            INSERT INTO product (name, description, price, created_at) VALUES ('Beef - Short Ribs', 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '5.59', '2017-09-29 14:01:48');
            INSERT INTO product (name, description, price, created_at) VALUES ('Vodka - Hot, Lnferno', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', '2.38', '2017-08-10 05:30:05');
            INSERT INTO product (name, description, price, created_at) VALUES ('Appetizer - Asian Shrimp Roll', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', '8.71', '2017-02-09 20:08:20');
            INSERT INTO product (name, description, price, created_at) VALUES ('Vaccum Bag 10x13', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', '9.15', '2017-07-12 13:55:39');
            INSERT INTO product (name, description, price, created_at) VALUES ('Nut - Pumpkin Seeds', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '1.20', '2017-04-14 06:40:47');
            INSERT INTO product (name, description, price, created_at) VALUES ('Sweet Pea Sprouts', 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '0.16', '2018-01-01 07:58:17');
            INSERT INTO product (name, description, price, created_at) VALUES ('Shrimp - Black Tiger 13/15', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.', '8.48', '2017-04-03 14:17:20');
            INSERT INTO product (name, description, price, created_at) VALUES ('Cleaner - Comet', 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.', '5.75', '2017-08-07 12:05:11');
            INSERT INTO product (name, description, price, created_at) VALUES ('Aspic - Light', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', '7.03', '2018-01-02 10:29:00');
            INSERT INTO product (name, description, price, created_at) VALUES ('Long Island Ice Tea', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '1.10', '2018-01-20 20:53:38');
            INSERT INTO product (name, description, price, created_at) VALUES ('Beer - Original Organic Lager', 'In hac habitasse platea dictumst.', '8.03', '2018-01-17 02:35:07');
            INSERT INTO product (name, description, price, created_at) VALUES ('Yogurt - Raspberry, 175 Gr', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', '3.29', '2017-12-23 05:39:44');
            INSERT INTO product (name, description, price, created_at) VALUES ('Fireball Whisky', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', '6.26', '2017-02-15 22:32:46');
            INSERT INTO product (name, description, price, created_at) VALUES ('Beef - Ground, Extra Lean, Fresh', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '4.44', '2017-03-20 16:47:56');
            INSERT INTO product (name, description, price, created_at) VALUES ('Emulsifier', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '6.06', '2017-06-08 21:58:09');
            INSERT INTO product (name, description, price, created_at) VALUES ('Lentils - Green, Dry', 'Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '9.78', '2017-02-10 19:34:35');
            INSERT INTO product (name, description, price, created_at) VALUES ('Cookie Trail Mix', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', '2.32', '2017-08-04 08:47:02');
            INSERT INTO product (name, description, price, created_at) VALUES ('Turkey - Breast, Smoked', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '5.86', '2017-09-28 10:57:39');
            INSERT INTO product (name, description, price, created_at) VALUES ('Tea - Decaf Lipton', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', '7.02', '2017-06-27 14:31:47');
            INSERT INTO product (name, description, price, created_at) VALUES ('Syrup - Monin - Passion Fruit', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', '4.79', '2017-07-12 03:44:42');
            INSERT INTO product (name, description, price, created_at) VALUES ('Cookie Dough - Oatmeal Rasin', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.', '5.27', '2017-10-12 18:06:57');
            INSERT INTO product (name, description, price, created_at) VALUES ('Wonton Wrappers', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '3.63', '2017-10-31 12:56:10');
            INSERT INTO product (name, description, price, created_at) VALUES ('Soap - Pine Sol Floor Cleaner', 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', '2.05', '2017-09-09 19:20:00');
            INSERT INTO product (name, description, price, created_at) VALUES ('Chef Hat 20cm', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '4.30', '2017-08-05 11:17:39');
            INSERT INTO product (name, description, price, created_at) VALUES ('Plasticknivesblack', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '0.47', '2017-05-14 17:45:17');
            INSERT INTO product (name, description, price, created_at) VALUES ('Squash - Sunburst', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.', '8.35', '2017-04-08 07:52:20');
            INSERT INTO product (name, description, price, created_at) VALUES ('Flavouring - Orange', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '4.85', '2017-02-06 11:13:01');
            INSERT INTO product (name, description, price, created_at) VALUES ('Mushroom Morel Fresh', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2.68', '2017-11-20 18:33:47');
            INSERT INTO product (name, description, price, created_at) VALUES ('Capon - Breast, Double, Wing On', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', '1.30', '2017-05-16 20:35:42');
            INSERT INTO product (name, description, price, created_at) VALUES ('Wine - Zonnebloem Pinotage', 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', '9.60', '2017-09-15 23:09:23');
            INSERT INTO product (name, description, price, created_at) VALUES ('Lid Coffee Cup 8oz Blk', 'Morbi a ipsum. Integer a nibh. In quis justo.', '2.15', '2017-06-25 09:13:35');
            INSERT INTO product (name, description, price, created_at) VALUES ('Cheese - Cheddar, Medium', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', '8.44', '2017-06-28 06:27:55');
            INSERT INTO product (name, description, price, created_at) VALUES ('Sugar - Monocystal / Rock', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', '2.78', '2017-11-09 11:28:52');
            INSERT INTO product (name, description, price, created_at) VALUES ('Onions - Pearl', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', '7.35', '2017-02-07 22:33:05');
            INSERT INTO product (name, description, price, created_at) VALUES ('Higashimaru Usukuchi Soy', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', '7.87', '2017-12-27 11:59:14');
            INSERT INTO product (name, description, price, created_at) VALUES ('Rabbit - Saddles', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', '6.01', '2017-02-20 23:46:20');
            INSERT INTO product (name, description, price, created_at) VALUES ('Napkin - Cocktail,beige 2 - Ply', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', '0.85', '2018-01-03 14:47:35');
            INSERT INTO product (name, description, price, created_at) VALUES ('Lamb - Whole, Fresh', 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '0.49', '2017-12-22 15:03:08');
            INSERT INTO product (name, description, price, created_at) VALUES ('Pumpkin - Seed', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.', '1.82', '2017-09-26 15:12:07');
            INSERT INTO product (name, description, price, created_at) VALUES ('Sour Puss - Tangerine', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', '9.12', '2017-10-28 22:38:37');
            INSERT INTO product (name, description, price, created_at) VALUES ('Lobster - Tail 6 Oz', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', '2.33', '2017-08-29 07:04:11');
            INSERT INTO product (name, description, price, created_at) VALUES ('Ginger - Crystalized', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', '6.47', '2017-02-14 11:42:15');
            INSERT INTO product (name, description, price, created_at) VALUES ('Nut - Pistachio, Shelled', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '1.83', '2017-05-22 15:12:50');
            INSERT INTO product (name, description, price, created_at) VALUES ('Soda Water - Club Soda, 355 Ml', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '7.56', '2017-02-08 09:22:35');
            INSERT INTO product (name, description, price, created_at) VALUES ('Wine - Zonnebloem Pinotage', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.', '9.22', '2017-05-03 18:09:22');
            INSERT INTO product (name, description, price, created_at) VALUES ('Pepsi - 600ml', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '8.43', '2017-03-06 18:35:19');
            INSERT INTO product (name, description, price, created_at) VALUES ('Cheese - Brie,danish', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', '9.47', '2017-12-19 12:45:43');
            INSERT INTO product (name, description, price, created_at) VALUES ('Pomello', 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', '0.63', '2017-12-20 10:19:00');
            INSERT INTO product (name, description, price, created_at) VALUES ('Bar Mix - Pina Colada, 355 Ml', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '4.45', '2017-04-20 21:48:31');
            INSERT INTO product (name, description, price, created_at) VALUES ('Nut - Pumpkin Seeds', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '2.49', '2017-10-27 06:00:52');
            INSERT INTO product (name, description, price, created_at) VALUES ('Corn Shoots', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2.93', '2017-07-16 11:07:55');
            INSERT INTO product (name, description, price, created_at) VALUES ('Chocolate Bar - Smarties', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '1.71', '2017-08-17 17:50:24');
            INSERT INTO product (name, description, price, created_at) VALUES ('Bread Fig And Almond', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', '5.81', '2017-06-20 23:22:51');
            INSERT INTO product (name, description, price, created_at) VALUES ('Beef - Kindney, Whole', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', '6.52', '2017-09-24 10:06:49');
            INSERT INTO product (name, description, price, created_at) VALUES ('Beer - Camerons Auburn', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', '6.19', '2017-09-02 02:32:26');
            INSERT INTO product (name, description, price, created_at) VALUES ('Pastry - Baked Scones - Mini', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '8.85', '2018-01-18 10:09:48');
            INSERT INTO product (name, description, price, created_at) VALUES ('Sponge Cake Mix - Vanilla', 'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', '1.30', '2017-07-08 00:32:33');
            INSERT INTO product (name, description, price, created_at) VALUES ('Parasol Pick Stir Stick', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', '0.83', '2017-10-12 17:48:14');";

        $this->addSql($fixtures);
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        $this->addSql("TRUNCATE TABLE product;");
    }
}
